### ISSUE TITLE
FLANN 1.8.4 tests fail on Ubuntu 10.04

### ISSUE THREAD

**Issue by gammell** [mariusmuja/flann#130]
I'm trying to build FLANN 1.8.4 on a 64 bit installation of Ubuntu 10.04 (I cannot upgrade for the time being). It appears to compile fine using:

```
mkdir build
cd build
cmake -D BUILD_MATLAB_BINDINGS=OFF -D ..
make
```

with the following configuration

```
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PythonInterp: /usr/bin/python2.6
-- Found HDF5: debug;/usr/lib/libhdf5_hl.so;/usr/lib/libhdf5.so;optimized;/usr/lib/libhdf5_hl.so;/usr/lib/libhdf5.so
-- Found GTest: /usr/lib/libgtest.so
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- I could not find the latex2html command.
-- Install prefix: /usr/local
-- Build type: RelWithDebInfo
-- Building C bindings: ON
-- Building python bindings: ON
-- Building matlab bindings: OFF
-- Building CUDA library: OFF
-- Using OpenMP support: ON
-- Using MPI support: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/flann-1.8.4-src/build
```

I have been unable to run the tests however.

```
[  4%] Built target flann_s
[  4%] Built target flann
Scanning dependencies of target pyunit_test_clustering.py
[  4%] Running pyunit test(s) test_clustering.py
.........
----------------------------------------------------------------------
Ran 9 tests in 0.231s

OK
[  8%] Built target pyunit_test_clustering.py
Scanning dependencies of target dataset_brief100K.h5
[  8%] Built target dataset_brief100K.h5
[ 13%] Built target flann_cpp_s
[ 13%] Built target flann_cpp
Scanning dependencies of target flann_multithreaded_test
[ 17%] Building CXX object test/CMakeFiles/flann_multithreaded_test.dir/flann_multithreaded_test.cpp.o
Linking CXX executable ../../test/flann_multithreaded_test
[ 17%] Built target flann_multithreaded_test
Scanning dependencies of target flann_linear_test
[ 21%] Building CXX object test/CMakeFiles/flann_linear_test.dir/flann_linear_test.cpp.o
/home/user/flann-1.8.4-src/test/flann_linear_test.cpp: In constructor ‘Linear_SIFT10K::Linear_SIFT10K()’:
/home/user/flann-1.8.4-src/test/flann_linear_test.cpp:16: error: class ‘Linear_SIFT10K’ does not have any field named ‘DatasetTestFixture’
/home/user/flann-1.8.4-src/test/flann_linear_test.cpp:16: error: no matching function for call to ‘DatasetTestFixture<float, float>::DatasetTestFixture()’
/home/user/flann-1.8.4-src/test/flann_tests.h:653: note: candidates are: DatasetTestFixture<ElementType, DistanceType>::DatasetTestFixture(const std::string&) [with ElementType = float, DistanceType = float]
/home/user/flann-1.8.4-src/test/flann_tests.h:640: note:                 DatasetTestFixture<float, float>::DatasetTestFixture(const DatasetTestFixture<float, float>&)
/home/user/flann-1.8.4-src/test/flann_linear_test.cpp: In constructor ‘Linear_SIFT100K::Linear_SIFT100K()’:
/home/user/flann-1.8.4-src/test/flann_linear_test.cpp:58: error: class ‘Linear_SIFT100K’ does not have any field named ‘DatasetTestFixture’
/home/user/flann-1.8.4-src/test/flann_linear_test.cpp:58: error: no matching function for call to ‘DatasetTestFixture<float, float>::DatasetTestFixture()’
/home/user/flann-1.8.4-src/test/flann_tests.h:653: note: candidates are: DatasetTestFixture<ElementType, DistanceType>::DatasetTestFixture(const std::string&) [with ElementType = float, DistanceType = float]
/home/user/flann-1.8.4-src/test/flann_tests.h:640: note:                 DatasetTestFixture<float, float>::DatasetTestFixture(const DatasetTestFixture<float, float>&)
/home/user/flann-1.8.4-src/test/flann_linear_test.cpp: In constructor ‘Linear_SIFT10K_byte::Linear_SIFT10K_byte()’:
/home/user/flann-1.8.4-src/test/flann_linear_test.cpp:74: error: class ‘Linear_SIFT10K_byte’ does not have any field named ‘DatasetTestFixture’
/home/user/flann-1.8.4-src/test/flann_linear_test.cpp:74: error: no matching function for call to ‘DatasetTestFixture<unsigned char, float>::DatasetTestFixture()’
/home/user/flann-1.8.4-src/test/flann_tests.h:653: note: candidates are: DatasetTestFixture<ElementType, DistanceType>::DatasetTestFixture(const std::string&) [with ElementType = unsigned char, DistanceType = float]
/home/user/flann-1.8.4-src/test/flann_tests.h:640: note:                 DatasetTestFixture<unsigned char, float>::DatasetTestFixture(const DatasetTestFixture<unsigned char, float>&)
/home/user/flann-1.8.4-src/test/flann_linear_test.cpp: In constructor ‘Linear_SIFT100K_byte::Linear_SIFT100K_byte()’:
/home/user/flann-1.8.4-src/test/flann_linear_test.cpp:90: error: class ‘Linear_SIFT100K_byte’ does not have any field named ‘DatasetTestFixture’
/home/user/flann-1.8.4-src/test/flann_linear_test.cpp:90: error: no matching function for call to ‘DatasetTestFixture<unsigned char, float>::DatasetTestFixture()’
/home/user/flann-1.8.4-src/test/flann_tests.h:653: note: candidates are: DatasetTestFixture<ElementType, DistanceType>::DatasetTestFixture(const std::string&) [with ElementType = unsigned char, DistanceType = float]
/home/user/flann-1.8.4-src/test/flann_tests.h:640: note:                 DatasetTestFixture<unsigned char, float>::DatasetTestFixture(const DatasetTestFixture<unsigned char, float>&)
make[3]: *** [test/CMakeFiles/flann_linear_test.dir/flann_linear_test.cpp.o] Error 1
make[2]: *** [test/CMakeFiles/flann_linear_test.dir/all] Error 2
make[1]: *** [test/CMakeFiles/test.dir/rule] Error 2
make: *** [test] Error 2
```

I have deleted the build folder and started from scratch without the python bindings which I don't really need:

```
cmake -D BUILD_MATLAB_BINDINGS=OFF -D BUILD_PYTHON_BINDINGS=OFF ..
```

while runs a different test first, which also fails:

```
[  4%] Built target flann_s
[  4%] Built target flann
Scanning dependencies of target pyunit_test_nn_autotune.py
[  4%] Running pyunit test(s) test_nn_autotune.py
.F.F.
======================================================================
FAIL: test_nn_autotune_100d_1000pt (__main__.Test_PyFLANN_nn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/flann-1.8.4-src/test/test_nn_autotune.py", line 26, in test_nn_autotune_100d_1000pt
    self.__nd_random_test_autotune(100, 1000)
  File "/home/user/flann-1.8.4-src/test/test_nn_autotune.py", line 74, in __nd_random_test_autotune
    'failed #1: targ_prec=%f, N=%d,correctness=%f' % (tp, N, correctness))
AssertionError: failed #1: targ_prec=0.700000, N=1000,correctness=0.594000

======================================================================
FAIL: test_nn_autotune_500d_100pt (__main__.Test_PyFLANN_nn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/flann-1.8.4-src/test/test_nn_autotune.py", line 29, in test_nn_autotune_500d_100pt
    self.__nd_random_test_autotune(500, 100)
  File "/home/user/flann-1.8.4-src/test/test_nn_autotune.py", line 74, in __nd_random_test_autotune
    'failed #1: targ_prec=%f, N=%d,correctness=%f' % (tp, N, correctness))
AssertionError: failed #1: targ_prec=0.700000, N=100,correctness=0.250000

----------------------------------------------------------------------
Ran 5 tests in 166.836s

FAILED (failures=2)
make[3]: *** [test/CMakeFiles/pyunit_test_nn_autotune.py] Error 1
make[2]: *** [test/CMakeFiles/pyunit_test_nn_autotune.py.dir/all] Error 2
make[1]: *** [test/CMakeFiles/test.dir/rule] Error 2
make: *** [test] Error 2
```

The system has gcc 4.4.3, cmake 2.8.0, gtest 1.3.0 and hdf5 1.8.4 if that's at all helpful.

Any advice would be appreciated.
Thanks.

**Comment by samhodge** [comment]
This issue just caught me out today.

Any idea of a fix, I am compiling from source under centos 6.2 with gcc 4.1 and 4.4 and python 2.7.5 and numpy 1.7.1

**Comment by samhodge** [comment]
======================================================================
FAIL: test_nn_autotune_100d_1000pt (__main__.Test_PyFLANN_nn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/rsp/tmp/weekly/samh/octobuild/flann/source-1.8.4/flann-1.8.4-src/test/test_nn_autotune.py", line 26, in test_nn_autotune_100d_1000pt
    self.__nd_random_test_autotune(100, 1000)
  File "/rsp/tmp/weekly/samh/octobuild/flann/source-1.8.4/flann-1.8.4-src/test/test_nn_autotune.py", line 74, in __nd_random_test_autotune
    'failed #1: targ_prec=%f, N=%d,correctness=%f' % (tp, N, correctness))
AssertionError: failed #1: targ_prec=0.700000, N=1000,correctness=0.594000

======================================================================
FAIL: test_nn_autotune_500d_100pt (__main__.Test_PyFLANN_nn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/rsp/tmp/weekly/samh/octobuild/flann/source-1.8.4/flann-1.8.4-src/test/test_nn_autotune.py", line 29, in test_nn_autotune_500d_100pt
    self.__nd_random_test_autotune(500, 100)
  File "/rsp/tmp/weekly/samh/octobuild/flann/source-1.8.4/flann-1.8.4-src/test/test_nn_autotune.py", line 74, in __nd_random_test_autotune
    'failed #1: targ_prec=%f, N=%d,correctness=%f' % (tp, N, correctness))
AssertionError: failed #1: targ_prec=0.700000, N=100,correctness=0.250000

----------------------------------------------------------------------
Ran 5 tests in 168.214s

FAILED (failures=2)
[80002 refs]
make[3]: *** [test/CMakeFiles/pyunit_test_nn_autotune.py] Error 1
make[2]: *** [test/CMakeFiles/pyunit_test_nn_autotune.py.dir/all] Error 2
make[1]: *** [test/CMakeFiles/test.dir/rule] Error 2
make: *** [test] Error 2
