### ISSUE TITLE
Unable to run tests (`make test`)

### ISSUE THREAD

**Issue by seth-planet** [mariusmuja/flann#316]
I have some significant issues when attempting to run tests. Is anyone else seeing these?

Firstly, I'm unable to run the ruby tests due to the use of the `rspec-longrun` package and it's incompatibility with the latest version of rspec:
```
/usr/local/Cellar/ruby/2.4.0/bin/ruby -I/usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib:/usr/local/lib/ruby/gems/2.4.0/gems/rspec-support-3.5.0/lib /usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/exe/rspec spec/flann_spec.rb spec/index_spec.rb
/usr/local/lib/ruby/gems/2.4.0/gems/rspec-longrun-1.0.1/lib/rspec/longrun/formatter.rb:55:in `alias_method': undefined method `cyan' for class `RSpec::Longrun::Formatter' (NameError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-longrun-1.0.1/lib/rspec/longrun/formatter.rb:55:in `alias_missing_method'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-longrun-1.0.1/lib/rspec/longrun/formatter.rb:59:in `<class:Formatter>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-longrun-1.0.1/lib/rspec/longrun/formatter.rb:6:in `<module:Longrun>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-longrun-1.0.1/lib/rspec/longrun/formatter.rb:4:in `<module:RSpec>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-longrun-1.0.1/lib/rspec/longrun/formatter.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-longrun-1.0.1/lib/rspec/longrun.rb:2:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-longrun-1.0.1/lib/rspec/longrun.rb:2:in `<top (required)>'
	from /Users/sprice/co_proj/flann/src/ruby/spec/spec_helper.rb:29:in `require'
	from /Users/sprice/co_proj/flann/src/ruby/spec/spec_helper.rb:29:in `<top (required)>'
	from /Users/sprice/co_proj/flann/src/ruby/spec/flann_spec.rb:28:in `require'
	from /Users/sprice/co_proj/flann/src/ruby/spec/flann_spec.rb:28:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>'
/usr/local/Cellar/ruby/2.4.0/bin/ruby -I/usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib:/usr/local/lib/ruby/gems/2.4.0/gems/rspec-support-3.5.0/lib /usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/exe/rspec spec/flann_spec.rb spec/index_spec.rb failed
make[3]: *** [test/CMakeFiles/flann_ruby_spec] Error 1
make[2]: *** [test/CMakeFiles/flann_ruby_spec.dir/all] Error 2
make[1]: *** [test/CMakeFiles/test.dir/rule] Error 2
make: *** [test] Error 2
```

It looks like the package has been depreciated elsewhere for this reason:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816627

Secondly, once I disable the ruby tests, I'm seeing a failure of the python tests that looks like this:
```...F.
======================================================================
FAIL: test_nn_autotune_500d_100pt (__main__.Test_PyFLANN_nn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sprice/co_proj/flann/test/test_nn_autotune.py", line 29, in test_nn_autotune_500d_100pt
    self.__nd_random_test_autotune(500, 100)
  File "/Users/sprice/co_proj/flann/test/test_nn_autotune.py", line 74, in __nd_random_test_autotune
    'failed #1: targ_prec=%f, N=%d,correctness=%f' % (tp, N, correctness))
AssertionError: failed #1: targ_prec=0.700000, N=100,correctness=0.620000

----------------------------------------------------------------------
Ran 5 tests in 344.006s

FAILED (failures=1)
make[3]: *** [test/CMakeFiles/pyunit_test_nn_autotune.py] Error 1
make[2]: *** [test/CMakeFiles/pyunit_test_nn_autotune.py.dir/all] Error 2
make[1]: *** [test/CMakeFiles/test.dir/rule] Error 2
make: *** [test] Error 2
```

I'm not sure what to make of this. It looks like everything is otherwise running correctly, and there is simply a failure in python FLANN. Attempting to revert commits back several years still gives this result.

So, if I then disable the python tests, most of the rest of the tests pass. Until I hit the LSH tests:
```[----------] Global test environment tear-down
[==========] 8 tests from 1 test case ran. (26034 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 7 tests, listed below:
[  FAILED  ] LshIndex_Brief100K.TestSearch
[  FAILED  ] LshIndex_Brief100K.TestSearch2
[  FAILED  ] LshIndex_Brief100K.TestAddIncremental
[  FAILED  ] LshIndex_Brief100K.TestIncremental2
[  FAILED  ] LshIndex_Brief100K.TestSave
[  FAILED  ] LshIndex_Brief100K.TestCopy
[  FAILED  ] LshIndex_Brief100K.TestCopy2

 7 FAILED TESTS
make[3]: *** [test/CMakeFiles/test_flann_lsh_test] Error 1
make[2]: *** [test/CMakeFiles/test_flann_lsh_test.dir/all] Error 2
make[1]: *** [test/CMakeFiles/test.dir/rule] Error 2
make: *** [test] Error 2
```

The LSH test started failing at this commit in July, 2015:
https://github.com/mariusmuja/flann/commit/c2d2e473ec53a28d86b9bda0146124d9f1cafdb0

Am I doing everything right here? I'd like to do a bunch of work on getting FLANN running on the OpenCL, but I'd like to know everything is running correctly first.

**Comment by a2975667** [comment]
Hello, I also met the same issue. Is there any current workarounds?

**Comment by seth-planet** [comment]
I just temporarily deleted the failing tests because I was working with different parts of the library.
